project:
    type: book

execute:
    freeze: auto

book:
    page-navigation: true
    title: "Projekt Dokumentation"
    description: "Entwicklung eines Chatbot's am Beispiel des Unternehmens FESTOOL"
    site-url: "https://llm-hdm.github.io/documentation/"
    repo-url: https://github.com/llm-hdm/documentation
    repo-actions: [edit, issue]
    open-graph: true
    image: "/images/logo.png"
    favicon: "/images/logo.png"
    search:
        type: overlay
    page-footer:
        left: |
            © Team X, 2023
        center:
            - text: "Home"
              href: index.qmd
            - text: "Einleitung"
              href: einleitung.qmd
        right:
            - icon: person-circle
            - text: "Moodle"
              href: https://moodle.hdm-stuttgart.de/login/index.php
              aria-label: Moodle
    #    background: "#325b74"
    chapters:
        - index.qmd
        - einleitung.qmd
        - grundlagen.qmd
        - ziele_und_anforderungen.qmd
        - design_und_entwicklung.qmd
        - evaluation.qmd
        - fazit.qmd
        - links.qmd

format:
    html:
        toc: true
        theme:
            light: [cosmo, style/style.scss]
            dark: [cosmo, style/style.scss, style/dark.scss]
        mainfont: "Atkinson Hyperlegible"
        code-copy: true
        code-overflow: wrap

bibliography: references.bib
