# Evaluation of the Model

Wir haben uns dazu entschieden, bei der Evaluation des Chatbots auf den Produktbereich "Sägen" zu fokussieren.
Die Vorgehensweise ist auf andere Produktkategorien anwendbar.

## Richtigkeit und Verlässlichkeit des Chatbots

**Testszenario 1**

Prompt: Ich suche eine mobile Tischkreissäge die ich mit auf die Baustelle nehmen kann. Am besten sollte Sie einen Akku haben und der Sägeblattwechsel sollte schnell gehen. Wichtig ist auch, dass ich die Tischkreissäge einfach transportieren kann und evlt. mit meinem Smartphone verbinden kann.

**Testszenario 2**

Promt: Ich suche eine Tauchsäge ohne Akku. Wichtig ist, dass die Säge bei anhalten schnell stopppt und über eine Temperaturüberwachung verfügt. Zudem sollte sie eine lange Lebensdauer haben.

**Testszenario 3**

Prompt: Ich suche eine Dämmstoffsäge mit Akku für die Baustelle. Sie sollte mobil sein, sodass ich sie auch einfach auf dem Gerüst benutzen kann.

**Testszenario 4**

Prompt: Ich brauche eine Schwertsäge mit hoher Schnitttiefe. Zudem wäre es gut, wenn die Säge zum Transport leichter als 11kg ist und ich auch Winkelschnitte ausführen kann.

## Manuelle Messung der Verbesserung der User Experience (UX):

**Testszenario 1:** Ein Kunde (Heimwerker) möchte eine allrounder Tauchsäge mit Akku.

**Manuell:**

_Vorgehensweise:_ Der User muss auf die Produktübersicht gehen und die Kachel "Sägen" wählen. Anschließend werden ihm sehr viele Geräte angeboten. Für einen Heimwerker ist die Auswahl enorm. Er benötigt Zeit um alles anzusehen. Um schneller vergleichen zu können Nutzt er die Vergleichs option, die Festool bereits auf ihrer seite anbietet.
Jetzt wählt er vier zufällige Modelle aus.
Schnell fällt auf, dass nach Auswahl aller Modelle bereits 40 Sekunden vergangen sind.
Jetzt gilt es, sich etwas auszukennen und die verschiedenen Features der Tauchsägen miteinander zu vergleichen. Dies dauert in unserem Test deutlich über 2 Minuten. DAbei fiel auch auf, dass es nur eine Tauchsäge mit Akku gibt. Das ist ein Pluspunkt der Vergleichsseite.
Alternativ kann der Kunde auch die Kachel 'Akkuwerkzeug' auswählen. Jedoch hat in unserem Test die Testperson den Reiter 'Sägen' gewählt.

_Dauer:_ > 4 Minuten

**Chatbot:**

_Prompt:_ Ich möchte eine allrounder Tauchsäge mit Akku für Heimwerker.

_Antwort:_ Für Heimwerker empfehle ich die Akku-Tauchsäge TSC 55 KEB-Basic. Sie bietet Sicherheit durch KickbackStop und flexible Anpassungen an das Material mit hoher Schnittleistung.

_Evaluation:_ Der Chatbot empfielt dem Heimwerker das einzige Modell das Festool anbietet, welches mit Akku betrieben werden kann. Der Bot verlinkt das passende Gerät gleich, dadurch ist eine Suche nicht nötig.
Für die Eingabe des Prompts wurden 15 Sekunden benötigt. Die Antwort kam nach weiteren 19 Sekunden.

_Dauer: 34 Sekunden_

**Fazit:** Der Chatbot beschleunigt die Auswahl von Produkten für Heimwerker oder solche Personen, die weniger vertraut mit Werkzeugen sind!

**Testszenario 2:** Ein Kunde sucht eine leichte Kappsäge für die Baustelle.

**Manuell:**

_Vorgehensweise:_ Der Kunde wählt den Reiter Werkzeuge und sieht bereits eine Kachel auf der eine Kappsäge abgebildet ist. Er wählt die Kachel aus und nutzt die Vergleichsfunktion für alle angebotenen Kappsägen (3 Stück). Nun kann er die Gewichte miteinander vergleichen. Nach lesen der Unterschiede entscheidet sich der Kunde für das Günstigere Modell mit Kabel.

_Dauer:_ 3,20 Minuten

**Chatbot:**

_Prompt:_ Ich suche eine leichte Kappsäge für die Baustelle.

_Antwort:_ Für den Einsatz auf der Baustelle empfehle ich Ihnen die Kapp-Zugsäge KAPEX KS 60 E. Sie ist kompakt, leicht und dank ihrer ergonomischen Tragegriffe einfach zu transportieren. Weitere Informationen finden Sie hier.

_Evaluation:_ Der Chatbot empfielt und verlinkt das extra für die Montage geeignete Modell ohne Akku. Zudem ist das Modell günstiger, als der Akku betriebene Bruder. Nach eingabe des Prompts (10 Sekunden) und der Antwort (12 Sekunden) kommt der Kunde in nur 22 Sekunden an das vorgeschlagene Modell. Die passende Säge hat er vorgeschlagen jedoch nicht erwähnt, dass es zwei Arten dieser Säge gibt. Eine Akku und eine Netz Variante.

_Dauer: 22 Sekunden_

**Fazit:** Der Bot empfielt dem Kunden _eine_ geeignete Säge. Dies ist eine brauchbare Antwort. Dennoch gibt es hier zwei Sägenn, die nahezu identisch sind. Der Hauptunterschied liegt bei der Stromzuführung. Der Bot empfiehlt jedoch die Säge, die auf der Produktseite mit "Verzichtet auf alles, was auf Montage überflüssig ist", beschrieben wird. Daher ist die Antwort in soweit korrekt. Jedoch wäre eine Erwähnung der Stromversorgung wünschenswert gewesen.
Dennoch ist der Kunde durch den Einsatz des Bots deutlich schneller zu einem Produkt gekommen als durch die manuelle Suche nach einer geeigneten Säge.

